apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
      - name: transaction-service
        image: transaction-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgresql:5432/banking_db"

---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: transaction-service